# You can create generators as much as you want.
# Important: All generators should be named "generator1", "generator2", etc. 
# You can define the spawnrates of any block in the blocks-section.
# The spawnrates are in percent, for example 57.3 are 57,3%.
# All values together should be 100%. If all values together are higher or lower as 100, the plugin would'nt work correctly.
# The permissions are custom, so you can make a generator for VIPS, and give them the permission "oregen.vip".
# Are you finish with configuring? Just type /customoregen to reload the plugin!

# Note: If the Island's owner is offline, the cobblestone generator would be choose the first Generator-Config.

generators:
  generator1:
    # default generator
    # name of the generator (does not need to be set, just for placeholders)
    label: "beginner"
    blocks:
    # Please use Bukkit-Blocknames. List: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    - STONE:100.0
    permission: ''
    # You can also define from what level the generator should be activated. Example: Leave all permissions empty and
    # only work with the island Level. The plugin would only consider the islandLevel then.
    unlock_islandLevel: -100000
  generator2:
    # vip generator, VIPS need generators.vip permission
    label: "expert"
    blocks:
    - IRON_ORE:4.0
    - STONE:95.9
    - DIAMOND_ORE:0.1
    permission: ''
    unlock_islandLevel: 10
  generator3:
    # vip generator, VIPS need generators.vip permission
    label: "monster"
    blocks:
    - IRON_ORE:5.0
    - GOLD_ORE:2.0
    - STONE:92.9
    - DIAMOND_ORE:0.1
    permission: ''
    unlock_islandLevel: 50
  generator4:
    # vip generator, VIPS need generators.vip permission
    label: "killer"
    blocks:
    - IRON_ORE:5.0
    - GOLD_ORE:2.0
    - STONE:91.9
    - DIAMOND_ORE:0.1
    - SAND:1.0
    permission: ''
    unlock_islandLevel: 100
  generator5:
    # vip generator, VIPS need generators.vip permission
    label: "exterminator"
    blocks:
    - IRON_ORE:5.0
    - GOLD_ORE:2.0
    - STONE:90.9
    - REDSTONE_ORE:1.0
    - DIAMOND_ORE:0.1
    - SAND:1.0
    permission: ''
    unlock_islandLevel: 150

# Here you can define worlds where the generator should not work
disabled-worlds:
- "world_nether"